//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalChallengeAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DADEntities1 : DbContext
    {
        public DADEntities1()
            : base("name=DADEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer0136> Customer0136 { get; set; }
        public virtual DbSet<Interest0136> Interest0136 { get; set; }
        public virtual DbSet<Record0136> Record0136 { get; set; }
        public virtual DbSet<Sale0136> Sale0136 { get; set; }
    }
}
