//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalChallengeAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale0136
    {
        public int CustNo { get; set; }
        public string RecordID { get; set; }
        public string DateOrdered { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customer0136 Customer0136 { get; set; }
        public virtual Record0136 Record0136 { get; set; }
    }
}
